In [1]:
import numpy as np

# operations on array

In [4]:
a = np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [6]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [7]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [8]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [9]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

# reshaping the array

In [10]:
# n(rows)*n(columns) = total_elements

In [11]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
a.shape

(12,)

In [13]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [14]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [16]:
b= np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [17]:
a+b ### (1+5 =6 , 2+6 =8 etc.)


array([[ 6,  8],
       [10, 12]])

In [18]:
a-b

array([[-4, -4],
       [-4, -4]])

In [19]:
a*b

array([[ 5, 12],
       [21, 32]])

In [20]:
a.dot(b) # for matrix multiplication

array([[19, 22],
       [43, 50]])

In [21]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [22]:
a

array([[1, 2],
       [3, 4]])

In [23]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [24]:
a**3

array([[ 1,  8],
       [27, 64]])

In [25]:
# linspace() --- it will return same gap values in a given range

In [26]:
a = np.linspace(1,2,5)
a  # diference is 0.25 in all 

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [27]:
# unique() --- it will provide an array i which it will return 3 array
# arr ---- return unique values
# return_index = True ---- return indexing of unique values 
# return_counts = True ----- return frequency of each unique values .

In [28]:
a = np. array([1,2,3,1,1,1,2,6,7])
a

array([1, 2, 3, 1, 1, 1, 2, 6, 7])

In [30]:
np.unique(a , return_index=True , return_counts=True)

(array([1, 2, 3, 6, 7]), array([0, 1, 2, 7, 8]), array([4, 2, 1, 1, 1]))

In [31]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
np.sum(a)

np.int64(45)

In [33]:
np.sum(a, axis=0) ## return column wise sum 

array([12, 15, 18])

In [34]:
np.sum(a, axis=1) ### return row wise sum

array([ 6, 15, 24])

# hstack and vstack

In [35]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)