In [1]:
#introduction to numpy--->
# numpy  is an open source library that is used for scientific library


In [ ]:
# how numpy is better than list ?
# 1. numpy is homogenous data type while list is heterogenous data type 
#2. numpy takes less memory while list takes more memory.
#3. numpy take less execution

In [20]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [18]:
a =[1,45,56,78]
type (a)
b = np.array(a)
type(b)

numpy.ndarray

In [6]:
a=[]
size= int (input("enter size:"))
for i in range(size):
    val = int(input("enter element:"))
    a.append(val)
b=np.array(a)
b


enter size: 3
enter element: 3
enter element: 3
enter element: 3


array([3, 3, 3])

In [19]:
type(b)

numpy.ndarray

In [14]:
a =[[1,2,3,4],[4,5,6,7],[7,8,9,8]]
a

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 8]]

In [15]:
b = np.array(a)
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 8]])

In [16]:
print("total rows and columns:" , b.shape)  
print("total elements:", b.size)
print("total dimension:", b.ndim) # ndim stand for 

total rows and columns: (3, 4)
total elements: 12
total dimension: 2


In [ ]:
#functions in numpy 

In [22]:
# 1. zeros() ---- it will create an array in which all the values in either one dimensional or multli dimensional will be 0.

In [23]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [24]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# 2. ones()----- it will create an array in which all the values will be 1 in either one dimensional or multi dimensional

In [26]:
a = np.ones(3)
a

array([1., 1., 1.])

In [27]:
a =np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
#3. eye()----
# matrix ---> diagonal position --- 1 
# it will create an array in which diagonal postional elements will be 1 and rest of all are 0.


In [29]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
a =np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# 4. diag()---- it willl create an array in which you can set custom values at diagonal position 

In [32]:
a = np.diag([1,4,5,6])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [33]:
# 5. random module --- it will return random numbers .

In [34]:
# a. randint()---- it will return random numbers in a given range .
#syntax:
# np.random.randint(min_number , max_number , total_number)

In [36]:
a = np.random.randint(1,10,3)
a

array([2, 1, 8], dtype=int32)

In [37]:
# b. rand()--- it will provide random numbers in range of 0 to 1..

In [38]:
a = np.random.rand(4)
a

array([0.18344316, 0.05724335, 0.77023619, 0.09922313])

In [39]:
# random numbers --- data use -- output 
# if random numbers refersh update -- previous output change 

In [ ]:
# c. seed()----- it wll fix our random generate data 

In [40]:
np.random.seed(15)
a= np.random.randint(1,10,3)
a

array([9, 6, 6], dtype=int32)

# view vs copy 

In [ ]:
# view --- copy --- changes made in copy does not affect the orignal

In [41]:
a = np.array ([1,2,3,4,5,6,7,8,])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
b= a[3:6]
b[:]=0
b

array([0, 0, 0])

In [43]:
a

array([1, 2, 3, 0, 0, 0, 7, 8])

In [44]:
a = np.array([1,2,3,4,5,6,7,8])
b=a[3:6].copy()
b[:]=0
b

array([0, 0, 0])

In [45]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])