In [1]:
import numpy as np

In [2]:
a=[1,45,32,45]
type(a)
b=np.array(a)
b

array([ 1, 45, 32, 45])

In [3]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b= np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print (b.shape)
print(b.size)
print(b.ndim)

(3, 3)
9
2


In [5]:
a=np.zeros((3,3))
a
           

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
a=np.ones((5,5))
a*=5
print(a)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [7]:
a=np.eye(4,4)
a*=2
a

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [8]:
a= np.diag([1,4,5,6])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [9]:
a= np.random.randint(1,10,5)
a

array([6, 9, 7, 1, 9], dtype=int32)

In [10]:
a=np.random.rand(3)
a

array([0.89700673, 0.56914008, 0.71293409])

In [11]:
np.random.seed(4)
a=np.random.randint(1,10,6)
a

array([8, 6, 2, 9, 8, 9], dtype=int32)

In [12]:
a=np.array([1,2,3,4,55,6,7,8])
a
b=a[3:6]
b[:]=0
b

array([0, 0, 0])

In [13]:
a

array([1, 2, 3, 0, 0, 0, 7, 8])

In [14]:
a= np.array([1,2,3,4,5,6,7,8])
b=a[3:6].copy()
b[:]=0
b

array([0, 0, 0])

In [15]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
a = np.arange(1,18)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [17]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True])

In [18]:
b=a>10
a[b]

array([11, 12, 13, 14, 15, 16, 17])

In [19]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [20]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a.shape

(9,)

In [22]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [24]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [25]:
a+b

array([[ 6,  8],
       [10, 12]])

In [26]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [27]:
a=  np.linspace(1,2,10)
a

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [28]:
a= np.array([1,2,3,4,1,1,1,2,6,7])
a

array([1, 2, 3, 4, 1, 1, 1, 2, 6, 7])

In [29]:
np.unique(a, return_index=True ,return_counts=True)

(array([1, 2, 3, 4, 6, 7]),
 array([0, 1, 2, 3, 8, 9]),
 array([4, 2, 1, 1, 1, 1]))

In [30]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
print(np.sum(a))

45


In [32]:
a=np.arange(1,4)
b=np.arange(4,7)
c=np.arange(7,10)
a,b,c
print(np.hstack((a,b,c)))
np.vstack((a,b,c))

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [34]:
a= np.random.randint(1,10,5)
a

array([3, 8, 8, 8, 9], dtype=int32)

In [35]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
a = np.ones(10)
print(a*2)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [37]:
a = np.arange(1,10)
print(a)
a=a.reshape(3,3)
print(a)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
a=np.random.rand(3,3)
a

array([[0.6329631 , 0.00515915, 0.57235649],
       [0.36149634, 0.60413194, 0.39176619],
       [0.81194775, 0.61252534, 0.26647378]])

In [39]:
# Q.8 Concatenate 2D array horizontally and vertically?

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])
print("Horizontal stack:-")
print(np.hstack((a,b,c)))
print("\nVertical stack:-")
print(np.vstack((a,b,c)))
     

Horizontal stack:-
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Vertical stack:-
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
#1.Create an array of 10 zeros and change the 5th value to 1.
a=np.zeros(10)
a
a[5]=1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [41]:
#Create a NumPy array with values from 10 to 49.
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [42]:
#Reverse a NumPy array (e.g., [1, 2, 3] to [3, 2, 1]).
a=np.array([1,2,3])
a=a[::-1]
a

array([3, 2, 1])

In [43]:
#Create a 3x3 matrix with values from 0 to 8
a=np.arange(0,9)
a=a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
#Create a 3x3 identity matrix using NumPy

a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
#Create a 10-element array and set all elements greater than 5 to 0.
a=np.arange(10)
a[a>5]=0
a

array([0, 1, 2, 3, 4, 5, 0, 0, 0, 0])

In [46]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
#Extract the diagonal of a matrix.
a = np.arange(1, 10).reshape(3, 3)
print(a)
diagonal = np.diag(a)
print(diagonal)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [48]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

v_stack = np.vstack((a, b))
h_stack = np.hstack((a, b))
print("Vertical Stack:\n", v_stack)
print("Horizontal Stack:\n", h_stack)


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [54]:
a=np.array([])
print(a)

[]
