In [1]:
# 1. statement to import numpy
import numpy as np 

In [2]:
#2 Create an array using numpy?

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
# 3 Create an array of 10 random integers?

a = np.random.randint(1, 10, 10)
print(a)
     

[6 9 4 5 9 8 5 1 7 1]


In [4]:
# 4 Create an array of elements from 10-20?

a = np.arange(10, 20)
print(a)
     

[10 11 12 13 14 15 16 17 18 19]


In [5]:
# 5 Create an array which contains value 5, 10 times?

a = np.ones(10)
print(a*5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [6]:
# 6. create a one dimensional array and convert that into 3*3 matrix?

a= np.arange(1,10)
print(a)
a = a.reshape(3,3)
print(a)
     


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#7 Create a 2D array of size 3*3 but all the elements should be between 0 to 1?

a = np.random.rand(3,3)
print(a)


[[0.10051398 0.70058002 0.61616781]
 [0.54875288 0.1081861  0.81762111]
 [0.78070335 0.63951981 0.77611614]]


In [10]:
# Q.8 Concatenate 2D array horizontally and vertically?

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])
print("Horizontal stack:-")
print(np.hstack((a,b,c)))
print("\nVertical stack:-")
print(np.vstack((a,b,c)))
     

Horizontal stack:-
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Vertical stack:-
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
